"""Agregar vehicle_type a trip_requests

Revision ID: 182b8c79191a
Revises: fd503613441b
Create Date: 2025-06-21 12:41:17.390896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182b8c79191a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_requests',sa.Column('vehicle_type', sa.String(length=20), nullable=False, server_default="auto"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_requests', 'vehicle_type')
    # ### end Alembic commands ###
